name: Beatled
options:
  bundleIdPrefix: com.beatled
  deploymentTarget:
    iOS: "26.0"
    macOS: "26.0"
  xcodeVersion: "26.0"
  generateEmptyDirectories: true

targets:
  Beatled:
    type: application
    supportedDestinations: [iOS, macOS]
    sources:
      - path: Beatled
        excludes:
          - Info.plist
    info:
      path: Beatled/Info.plist
      properties:
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        NSLocalNetworkUsageDescription: "Beatled connects to your local beat server."
        NSBonjourServices:
          - "_http._tcp"
          - "_https._tcp"
        UILaunchScreen: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.beatled.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: false
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
