variable_watch(ALSA_LIBRARIES)
variable_watch(PA_USE_ALSA)
variable_watch(PA_ALSA_DYNAMIC)

set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)

set(VCPKG_LIBRARY_LINKAGE static)
if(${PORT} MATCHES "portaudio")
    # set(VCPKG_LIBRARY_LINKAGE dynamic)
    set(PA_ALSA_DYNAMIC ON)
endif()


if(NOT CMAKE_HOST_SYSTEM_PROCESSOR)
    execute_process(COMMAND "uname" "-m" OUTPUT_VARIABLE CMAKE_HOST_SYSTEM_PROCESSOR OUTPUT_STRIP_TRAILING_WHITESPACE)
endif()
