name: CI

on:
  push:
    branches: [master, "feature/*"]
    paths:
      - "docs/**"
      - "Gemfile*"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "docs/**"
      - "Gemfile*"

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@12fd324f1d0b43274fdc8130f6980590a667c455 # v1
        with:
          ruby-version: '3.3' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
          working-directory: "${{ github.workspace }}/docs"
      - name: Build with Jekyll
        run: bundle exec jekyll build
